# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

SUCCESS = 0
GONE_AWAY = -1

UNKNOWN_ERROR = 1000
NOT_SUPPORT = 1001
BAD_REQUEST = 1002
QUERY_FAILED = 1003
CREATE_FAILED = 1004
DELETE_FAILED = 1005
UPDATE_FAILED = 1006
VALID_FAILED = 1007

# 参数相关
PARAMS_ERROR = 2000
PARAMS_VALID = 2001
PARAMS_NULL = 2002
ATTR_ERROR = 2003
VALUE_ERROR = 2004
FILE_INVALID = 2005
FILE_TOO_LARGE = 2006
FILE_NOT_FOUND = 2007
CODE_NOT_VALID = 2008
EMAIL_NOT_VALID = 2009
PHONE_NOT_VALID = 2010
ONLY_SUPPORT_XLSX = 2011

# 权限相关
NOT_AUTH = 3000
PERMISSION_DENIED = 3001
AUTH_FAILED = 3002
AUTH_EXPIRED = 3003
AUTH_LIMIT = 3004
LOGIN_FAILED = 3005
LOGIN_REQUIRED = 3006
USER_PASSWORD_FAILED = 3007
USER_PASSWORD_NULL = 3008
TOKEN_INVALID = 3009
TOKEN_EXPIRED = 3010
USER_EXIST = 3011
ACTIVE_USER = 3012
NOT_ACTIVE_USER = 3013
CHECK_PASS = 3014
CHECK_FAILED = 3015
REQUEST_FREQUENT = 3016
FREQUENT_UPPER_LIMIT = 3017
LOGIN_FAILED_TOO_MANY = 3018
USER_NOT_EXIST = 3019
USER_NOT_FOUND = 3020
LICENSE_EXPIRING = 3021
LICENSE_LIMIT = 3022

# 资源相关
DATABASE_ERROR = 4001
MYSQL_GONE_AWAY = 4002
CONNECT_TIMEOUT = 4003
SOURCE_NOT_FOUND = 4004
UPGRADE_FILE_INVALID = 4005
DATA_CONFLICT = 4006
DELETE_FORBIDDEN = 4007
NOT_ACTIVE_LINK = 4008
MENU_TOO_MANY = 4009

MESSAGE = {
    SUCCESS: '正常',

    GONE_AWAY: '服务器繁忙，请稍后再试',

    UNKNOWN_ERROR: '未知错误',
    NOT_SUPPORT: '暂不支持',
    BAD_REQUEST: '错误请求',
    QUERY_FAILED: '查询失败',
    CREATE_FAILED: '创建失败',
    DELETE_FAILED: '删除失败',
    UPDATE_FAILED: '更新失败',
    VALID_FAILED: '验证失败',

    PARAMS_ERROR: '参数错误',
    PARAMS_VALID: '无效参数',
    PARAMS_NULL: '参数为空',
    ATTR_ERROR: '属性错误',
    VALUE_ERROR: '属性值错误',
    FILE_INVALID: '文件无效',
    FILE_TOO_LARGE: '文件太大',
    FILE_NOT_FOUND: '无法找到文件',
    USER_EXIST: '用户已存在',
    ACTIVE_USER: '用户已激活',
    NOT_ACTIVE_USER: '用户未激活',
    CODE_NOT_VALID: '无效验证码',
    EMAIL_NOT_VALID: '邮箱地址不合法',
    PHONE_NOT_VALID: '手机号码不合法',
    ONLY_SUPPORT_XLSX: '仅支持xlsx格式',

    NOT_AUTH: '未认证，无权访问',
    PERMISSION_DENIED: '无访问权限',
    AUTH_FAILED: '认证授权失败',
    AUTH_EXPIRED: '认证已过期',
    AUTH_LIMIT: '认证受限',
    TOKEN_INVALID: '令牌无效',
    TOKEN_EXPIRED: '令牌已过期',
    CHECK_PASS: '审核通过',
    CHECK_FAILED: '审核未通过',
    REQUEST_FREQUENT: '请求过于频繁',
    FREQUENT_UPPER_LIMIT: '请求次数达到上限',
    LOGIN_FAILED: '登录失败',
    LOGIN_REQUIRED: '请登录',
    USER_PASSWORD_FAILED: '用户名或密码错误',
    USER_PASSWORD_NULL: '用户名或密码为空',
    LOGIN_FAILED_TOO_MANY: '连续登录失败超过 3 次，1 分钟内不允许再次登录',
    USER_NOT_EXIST: '用户已存在',
    USER_NOT_FOUND: '找不到用户',
    LICENSE_EXPIRING: '授权已过期或未授权，请联系管理员',
    LICENSE_LIMIT: '超过授权账户最大允许的用户数，请联系管理员',

    DATABASE_ERROR: '数据库错误',
    MYSQL_GONE_AWAY: '数据库连接失败',
    CONNECT_TIMEOUT: '连接超时',
    SOURCE_NOT_FOUND: '资源不存在',
    UPGRADE_FILE_INVALID: '升级文件无效',
    DATA_CONFLICT: '数据冲突',
    DELETE_FORBIDDEN: '禁止删除',
    NOT_ACTIVE_LINK: '激活链接无效或已过期',
    MENU_TOO_MANY: '定制菜单超过数量',
}
